services:
  backend-sharing-app:
    container_name: backend
    image: ghcr.io/juanpdn/backend-sharing-code-app:latest
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      MONGO_URI: "mongodb://mongoadmin:secret@mongodb:27017/codes?authSource=admin"
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
      MONGO_INITDB_ROOT_PASSWORD: "secret"
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data: